const falseResponses = [
  "Ooo kardeşim, cuma kalabalık olur diye erkenden mi gittin sen?",
  "Senin yüzünden cumayı kaçırdım sandım.",
  "Daha gelmedik. Sen yat ben uyandırırım seni.",
  "Ah keşke bee...",
  "Ben de isterdim gavurlar gibi Allah'a Şükür Bugün Cuma demeyi.",
  "Güneş batarken ardından tepelerin... Neyse...",
  "Bugün cuma mı mübarek?",
  "Sabret kardeşim, o günler de gelecek.",
  "Noel Baba değilim ama seni yaramazlar listeme yazdım. Çünkü bugün cuma değil.",
  "Bugün Black Friday (Kara Cuma) olsa şaşırmazdınız ama bugün cuma değil.",
  "Hemen kontrol ediyorum... Hayır, bugün hala cuma değil.",
  "Sen gelecekten mi geliyorsun? Cuma olmadı daha bize.",
  "Bugün cuma değil, bugün cuma değil, bugün cuma değil.",
  "Hepimiz sabırsızlanıyoruz, ama henüz cuma olmadı.",
  "Biri bu arkadaşa günleri öğretsin.",
  "Komadan mı uyandım kardeşim? Cuma değil bugün.",
  "O gün bugün mü? Değil.",
  "Bir tane takvim botu ekleyebilir miyiz? Belli ki günler karıştırılıyor bu sunucuda.",
  "Bir takvim botu değildik ama biz de biliriz bugünün cuma olmadığını.",
  "En son kontrol ettiğimde benim görevim bunu hatırlatmak değildi ama, bugün cuma değil.",
  "Bugün cuma değil. Olsaydı bilirdim.",
  "Bugün cuma değil. Seninle konuşmak istiyorum.",
  "Günler karışmış sende. Bugün cuma değil.",
  "5. günün şafağında doğuya bakın sözü bugün için geçerli değil. Çünkü bugün haftanın 5. günü değil.",
  "Tahminde bulundun, tutmadı. Olsun, sen pes etme.",
  "Bugün cuma değil ama sen yarın bir daha dene şansını.",
];

module.exports = falseResponses;
